version: '3.1'
services:
    mysql:
        image: mysql
        container_name: import-mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
        restart: always
        volumes:
          - /home/jonathan/Docker/Volumes/MySql:/var/lib/mysql
    app:
        image: ambientum/php:7.3-nginx
        container_name: import-app
        restart: always
        ports:
          - '${APP_PORT:-80}:8080'
        volumes:
          - .:/var/www/app
        links:
          - mysql
          - redis
    phpmyadmin:
        image: phpmyadmin
        container_name: import-phpmyadmin
        restart: always
        ports:
        - 8001:80
        environment:
        - PMA_ARBITRARY=1
        links:
            - mysql
