# For more information: https://laravel.com/docs/sail
version: '3'
services:
    php:
        image: ambientum/php:7.2-nginx
        container_name: import-app
        volumes:
          - .:/var/www/app
        ports:
        - "8080:8080"
        depends_on:
            - mysql
            - redis
    mysql:
        image: mysql
        container_name: import-mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'importxml'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        restart: always
        ports:
          - 3308:3306
        volumes:
            - /home/Volumes/MySql:/var/lib/mysql
    redis:
        image: 'redis:alpine'
        container_name: import-redis
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - /home/Volumes/redis:/data
    phpmyadmin:
        image: phpmyadmin
        container_name: import-phpmyadmin
        restart: always
        ports:
        - 8000:80
        environment:
        - PMA_ARBITRARY=1
        depends_on:
            - php
